### ISSUE TITLE
iotivity-constrained works on linux (loopback)

### ISSUE THREAD

**Issue by ustccw** [iotivity/iotivity-constrained#8]
Hello, when i try to make iotivivity-constrained project run on linux with loopback, there is one issue for you.

i wonder what happened on IPV4,so i did as following:
```
$cd ~/thompson/iotivity-constrained/port/linux
$make IPV4=1
$./server
$./client
```
it would not work well, and the client would print **Stopping OBSERVE**.
at the same time, i try to capture packet with wireshark, there would be no any IPV4 packet for it.
![Image of capture](https://github.com/ustccw/ShareRepo/blob/master/captureIOTivity.png)

what should i do when i want to make it run based on IPV4 rather than IPV6?

**Comment by kmaloor** [comment]
Hello,

Please try building the stack with DYNAMIC=1.
make IPV4=1 DYNAMIC=1.
That should work.

Just a little background: IoTivity-Constrained must support IPv6 all
the time, and only optionally supports IPv4 (by building with
IPV4=1). This is driven by the dictates of the OCF specification. 

So, including IPV4 in the build results in discovery requests sent
over both v4 and v6 interfaces, so double the buffers being consumed. 
config.h has a parameter OC_MAX_NUM_CONCURRENT_REQUEST with a default
value of 2 that is insufficient for this, and that is why the samples quit on lack of 
of free buffers. 
Setting that to 4, for eg., leaves enough free  buffers for the samples to run.

But since you’re running on Linux, you could simply build with DYNAMIC=1 to dynamically 
allocates buffers as required (no set limit) and the samples run.

**Comment by ustccw** [comment]
@kmaloor 
thanks a lot, it works well.
